listen: ":50051"
storage: "sqlite"
database_path: "./data/gobright.db"
log_file: "./server.log"
log_level: "info"           # Or "debug", etc.

tls:
  cert_file: "../certs/server.crt"
  key_file: "../certs/server.key"
  client_ca_file: ""  # Leave empty if mTLS not used

debug:
  enable_reflection: true