listen: ":50051"
log_file: "./server.log"
log_level: "debug"           # Or "debug", etc.

tls:
  cert_file: "../certs/server.crt"
  key_file: "../certs/server.key"
  client_ca_file: "../certs/ca.crt"  # Leave empty if mTLS not used

debug:
  enable_reflection: true

storage:
  engine: "victoriametrics"
  url: "http://localhost:8428"
  workers: 4
  queue_size: 100
  batch_size: 100
  batch_timeout: 500   # flush every 500ms if not full
  batch_retry: 3
  batch_interval: 1000 # 1s between retry attempts