routes:
  - id: notify-admins
    match:
      level: critical
      rule_id: high-cpu
      tags:
        env: prod
        team: ops
    actions:
      - type: webhook
        url: https://hooks.example.com/gosight
        headers:
          Authorization: "Bearer XYZ"

  - id: log-to-file
    match:
      level: warning
    actions:
      - type: script
        command: /opt/scripts/log_alert.sh

  - id: notify-local
    match:
      level: warning
      rule_id: high-mem-usage
      tags:
        env: test
    actions:
      - type: webhook
        url: http://localhost:9999/test-alert
        headers:
          Authorization: "Bearer test123"

  - id: local-slacktest
    match:
      level: warning
    actions:
      - type: webhook
        url: http://localhost:8080
